"""
Output Filter
==============
Scans and sanitizes LLM responses BEFORE they are displayed to the user.
This is the last line of defense against sensitive information disclosure
and improper output handling.

Framework alignment:
    OWASP LLM02 (Sensitive Information Disclosure):
        "Unintended disclosure or exposure of sensitive information during
        model operation." This module catches sensitive patterns that the
        LLM might include in its response — whether from tool output,
        training data leakage, or confabulation.

    OWASP LLM05 (Improper Output Handling):
        "Insufficient validation, sanitization, and handling of outputs
        generated by LLMs before they are passed downstream to other
        systems or components." Even though our agent doesn't pass output
        to downstream systems, we still sanitize to prevent information
        leakage to the user.

    NIST AI 600-1 §5.2, §5.5:
        Sensitive information disclosure and improper output handling
        mitigations.

    CSA AICM DSP-04:
        Data sanitization and protection controls.

DESIGN DECISION:
    We use PATTERN-BASED filtering, not LLM-based filtering. An LLM
    cannot reliably self-censor — it's the same stochastic system that
    might have leaked the data. Deterministic regex patterns are auditable
    and predictable. They won't catch everything, but they catch the
    common cases and are not bypassable by adversarial prompts.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field


@dataclass
class FilterResult:
    """Result of output filtering."""

    original_text: str
    filtered_text: str
    redactions: list[str]

    @property
    def was_modified(self) -> bool:
        return len(self.redactions) > 0


# --- Sensitive patterns ---
# Each tuple: (compiled regex, description, replacement)
# These patterns are designed to catch common sensitive data shapes.
# They are NOT exhaustive — defense in depth means we have other layers too.

_SENSITIVE_PATTERNS: list[tuple[re.Pattern[str], str, str]] = [
    # Unix passwd file entries (root:x:0:0:...)
    (
        re.compile(r"\b\w+:x:\d+:\d+:[^:]*:[^:]*:[^\n]*", re.MULTILINE),
        "Unix passwd entry",
        "[REDACTED: passwd entry]",
    ),
    # Unix shadow file entries
    (
        re.compile(r"\b\w+:\$\d+\$[^\s:]+:[^:]*(?::[^:]*){6,}", re.MULTILINE),
        "Unix shadow entry",
        "[REDACTED: shadow entry]",
    ),
    # Private keys (SSH, PGP, etc.)
    (
        re.compile(
            r"-----BEGIN\s+(?:RSA|DSA|EC|OPENSSH|PGP)?\s*PRIVATE KEY-----"
            r"[\s\S]*?"
            r"-----END\s+(?:RSA|DSA|EC|OPENSSH|PGP)?\s*PRIVATE KEY-----",
            re.MULTILINE,
        ),
        "Private key block",
        "[REDACTED: private key]",
    ),
    # AWS access keys (AKIA...)
    (
        re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
        "AWS access key",
        "[REDACTED: AWS key]",
    ),
    # AWS secret keys (40-char base64)
    (
        re.compile(r"\b[A-Za-z0-9/+=]{40}\b"),
        # This is intentionally broad — may have false positives,
        # which is acceptable for a security-first design.
        # We only flag it when it appears near AWS-related context.
        "Possible AWS secret key",
        "[REDACTED: possible secret key]",
    ),
    # Generic API keys/tokens (common patterns)
    (
        re.compile(r"\b(?:api[_-]?key|api[_-]?token|bearer)\s*[=:]\s*['\"]?[\w\-\.]{20,}['\"]?", re.IGNORECASE),
        "API key/token",
        "[REDACTED: API credential]",
    ),
    # Email addresses (PII)
    (
        re.compile(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b"),
        "Email address (PII)",
        "[REDACTED: email]",
    ),
    # IP addresses (internal network indicators)
    (
        re.compile(
            r"\b(?:10\.\d{1,3}\.\d{1,3}\.\d{1,3}|"
            r"172\.(?:1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3}|"
            r"192\.168\.\d{1,3}\.\d{1,3})\b"
        ),
        "Internal IP address",
        "[REDACTED: internal IP]",
    ),
    # Connection strings
    (
        re.compile(
            r"(?:mysql|postgresql|mongodb|redis|amqp)://[^\s]+",
            re.IGNORECASE,
        ),
        "Database connection string",
        "[REDACTED: connection string]",
    ),
    # JWT tokens
    (
        re.compile(r"\beyJ[A-Za-z0-9_-]+\.eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\b"),
        "JWT token",
        "[REDACTED: JWT token]",
    ),
]

# Patterns that indicate system prompt leakage (OWASP LLM07)
_PROMPT_LEAKAGE_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    (
        re.compile(r"(?i)my\s+system\s+prompt\s+(is|says|reads|contains)", re.IGNORECASE),
        "Possible system prompt disclosure",
    ),
    (
        re.compile(r"(?i)i\s+was\s+instructed\s+to", re.IGNORECASE),
        "Possible instruction disclosure",
    ),
    (
        re.compile(r"(?i)my\s+instructions\s+(are|say|tell|require)", re.IGNORECASE),
        "Possible instruction disclosure",
    ),
]


def filter_output(text: str, strict: bool = True) -> FilterResult:
    """
    Scan LLM output for sensitive patterns and redact them.

    Args:
        text: Raw LLM response text
        strict: If True, also flag suspicious AWS-like keys.
                If False, only flag clearly identifiable credentials.

    Returns:
        FilterResult with original text, filtered text, and list of
        redaction descriptions.
    """
    filtered = text
    redactions: list[str] = []

    # Apply sensitive pattern filters
    for pattern, description, replacement in _SENSITIVE_PATTERNS:
        if not strict and description == "Possible AWS secret key":
            continue  # Skip the broad pattern in non-strict mode
        matches = pattern.findall(filtered)
        if matches:
            filtered = pattern.sub(replacement, filtered)
            redactions.append(f"{description} ({len(matches)} instance(s))")

    # Check for system prompt leakage indicators
    for pattern, description in _PROMPT_LEAKAGE_PATTERNS:
        if pattern.search(filtered):
            redactions.append(f"⚠️  {description} (not redacted, flagged for review)")

    return FilterResult(
        original_text=text,
        filtered_text=filtered,
        redactions=redactions,
    )
